name: Generated Signed APK AAB (Upload - Create Artifact To GitHub Action)

env:
  main_project_module: app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' 
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Generate Signing Keystore
      - name: Generate signing keystore
        run: |
          keytool -genkeypair \
            -alias android-key \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -dname "CN=Android Debug,O=Android,C=US"
          cat debug.keystore | base64 -d > "$ANDROID_KEYSTORE_B64"
          
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew test

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create Signed APK Debug
      - name: Build and sign APK debug project - ${{ env.main_project_module }} module
        run: |
          ./gradlew assembleDebug

      - name: Build and sign APK release project - ${{ env.main_project_module }} module
        run: |
          ./gradlew assembleRelease

      - name: ZipAlign & Sign DEBUG APK
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: ${{ env.main_project_module }}/build/outputs/apk/debug
          signingKeyBase64: ${{ env.ANDROID_KEYSTORE_B64 }} 
          alias: android-key
          keyStorePassword: android
          keyPassword: android
          zipAlign: true

      - name: ZipAlign & Sign RELEASE APK
        uses: tiann/zipalign-sign-android-release@v1.1.4
        with:
          releaseDirectory: ${{ env.main_project_module }}/build/outputs/apk/release
          signingKeyBase64: ${{ env.ANDROID_KEYSTORE_B64 }} 
          alias: android-key
          keyStorePassword: android
          keyPassword: android
          zipAlign: true


      # Create Signed Bundle AAB Release
      - name: Build and sign app bundle release (AAB) - ${{ env.main_project_module }} module
        run: |
          ./gradlew ${{ env.main_project_module }}:bundleRelease
          tree app/build/outputs
          jarsigner \
            -verbose \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            ${{ env.main_project_module }}/build/outputs/bundle/release/app-release.aab \
            android-key

      # Upload Signed APK Debug
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - Signed APK(s) debug
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Upload Signed APK Release
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - Signed APK(s) release
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Upload Signed AAB Release
      - name: Upload AAB Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - Signed App Bundle(s) release
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/
